### ISSUE TITLE
create JAR for JAVA 1.7

### ISSUE THREAD

**Issue by venil7** [marzn/telegrambot-japi#1]
so it can be used for Android

**Comment by marzn** [comment]
Would you like to run an Telegram Bot on Android? I will build one for the next release, this will come end of september. If you need it earlier, you can clone the repo and build it by yourself. I hope this will help =)

**Comment by venil7** [comment]
Yes, need it for Android built against Java 1.6 or Java 1.7
I'd love to do it myself if I knew how
I'm happy to wait for end of September release, thank you.

**Comment by marzn** [comment]
Java 1.7 would not work cause we use the combination of Surfire and PowerMockito for some Tests. These will need Java >= 1.8.
A workaround for you is possible these one:
Clone the git repo, remove the tests, build it and there you go.
If you are using linux:

```
git clone https://github.com/marzn/telegrambot-japi.git
cd telegrambot-japi
rm -r src/test/java/*
```

Change java version in pom.xml and build it:

```
mvn clean install
```

After that you will find the build in the folder target
