### ISSUE TITLE
No getter methods for some model package classes

### ISSUE THREAD

**Issue by chalkpe** [marzn/telegrambot-japi#3]
![diagram](https://cloud.githubusercontent.com/assets/9481405/10277924/7f646e12-6b94-11e5-9114-b16ad1ff1a3d.png)

There are private fields on `Audio`, `Document`, `PhotoSize`, and `Sticker` classes, but no public getters on them. `Sticker` class don't even have `equals(Object)` and `hashCode()`.

I want to access to them, how can I do? =(

**Comment by marzn** [comment]
Accessing files:

Telegram added the possibility to download such files on 18. September. Now this can be add in this project as well.
See getFile here: https://core.telegram.org/bots/api#getfile

The idea before was, that a Bot may forward these files using the objects, but does not access them directly.
But as I said, this can be added now.

hashCode and equals for Sticker:

This can be quickly added. Eclipse will do that for u.

I will have a look at that stuff, but at the moment I an very busy. If u want, u can fork it and make a push request after implementation.

**Comment by chalkpe** [comment]
Thanks, I'll make a pull request soon!
