### ISSUE TITLE
Check Webserver http status error codes

### ISSUE THREAD

**Issue by edtruji** [marzn/telegrambot-japi#4]
504 Gateway Time Out
502 Bad gateway 
or similar will throw a JSONTokener error as JSONObject text must begin with '{'
Fix?
On file  de.vivistra.telegrambot.client.Bot.java

HttpEntity entity = response.getEntity();
// HTTP status codes
if( contains( response.getStatusLine().toString(), "200" ) ) {
// HTTP/1.1 200 OK - Normal status code
LOG.debug(response.getStatusLine());
} else {
LOG.error(response.getStatusLine());
throw new SocketException("Reset webserver connection...");
}

private boolean contains( String haystack, String needle ) {
haystack = haystack == null ? "" : haystack;
needle = needle == null ? "" : needle;
return haystack.toLowerCase().contains( needle.toLowerCase());
}
![badgateway](https://cloud.githubusercontent.com/assets/933041/10412978/112aa53e-6f67-11e5-952c-672925eefe54.PNG)

**Comment by marzn** [comment]
Please use the actual version. This is fixed since v1.0.
