### ISSUE TITLE
The chat->id sometimes is greater than 32 bits

### ISSUE THREAD

**Issue by LeonardoDemartino** [marzn/telegrambot-japi#6]
For example, on supergroups with url, getGroupChat().getId() return a number that doesn't fit in the Integer from Java and this API won't work there. Using Long or BigInteger should fix the issue.

Nice API btw.

**Comment by LeonardoDemartino** [comment]
https://core.telegram.org/bots/api#chat

Check id description for more information.

**Comment by marzn** [comment]
Thank you

**Comment by LeonardoDemartino** [comment]
You're welcome! But you have also to change it to Long in all classes and function that send something using an id. For example: public TextMessage(Integer recipient, String message)

This will need a huge refactor of the entire project I'm afraid.

**Comment by LeonardoDemartino** [comment]
I already did the changes, please add me as a contributor. :)

**Comment by marzn** [comment]
Could you make a pull request, please?
